# Generated by Django 5.2 on 2025-04-22 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_education_alter_resume_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='resume',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='job_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
